image: "gitlab.kent.ac.uk:4567/jna/astro/php7.1:dev"

cache:
  key: "$CI_BUILD_REF_NAME-assets"
  paths:
    - $HOME/.composer/cache
    - vendor/
    - node_modules/

services:
  - mysql:latest
  - redis:latest
variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: test
  REDIS_LIB: predis
  REDIS_HOST: redis

before_script:
  - php --version
  - composer --version
  - yarn --version
  - mv .env.gitlab .env
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$CI_SSH_KEY")
  - composer config -g github-oauth.github.com ${GITHUB_TOKEN}
  - composer validate --no-check-all --ansi
  - composer install --prefer-dist
  - yarn install

after_script:
  - rm -rf node_modules .git

stages:
  - test
  - build

test:
  stage: test
  script:
    - php artisan key:generate
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
    - yarn run validate

artifacts-experimental:
  stage: build
  script:
    - echo "Ready to 'artifact!'"
  artifacts:
    paths:
      - ./
    expire_in: 1 week
  except:
    - develop
    - master

artifacts-develop:
  stage: build
  script:
    - echo "Ready to 'artifact!'"
  artifacts:
    paths:
      - ./
    expire_in: 3 months
  only:
    - develop

artifacts-master:
  stage: build
  script:
    - echo "Ready to 'artifact!'"
  artifacts:
    paths:
      - ./
    expire_in: 6 months
  only:
    - master